import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import React, { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const [state, setState] = useState();
  function handleClick() {
    router.push("jistix://jistix/barcode");
  }

  React.useEffect(() => {
    const { code } = router.query;
    if (code) {
      setState(code);
    }
  }, []);
 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <div className="home">
        <div className="links">
          {state ? <h1>Your barcode is: {state}</h1> : null}
          <button className='button' onClick={handleClick}>Scan QR Code</button>
        </div>
      </div>
      <br />
      
    </>
    </>
  )
}


export async function getServerSideProps(context) {
  const query = context.query;

  return {
    props: {
      query,
    }, // will be passed to the page component as props
  };
}